import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import CartProvider from "@/components/Providers";
import ShoppingCartModal from "@/components/ShoppingCartModal";

export const metadata: Metadata = {
  title: "NextEcommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          {children}
          <ShoppingCartModal />
        </CartProvider>
      </body>
    </html>
  );
};